name: Release & Package

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.2.3)'
        required: true
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-dev libboost-concept-dev
          
      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure Project
        run: |
          cmake -B build -S . \
            -DBoost_DEBUG=ON \
            -DBoost_INCLUDE_DIR=/usr/include

      - name: Build and Package .deb
        run: |
          cmake --build build --target package

      - name: Set tag name
        id: set_tag
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag_name=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
          else
            echo "No valid tag found. Skipping release creation."
            exit 0
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          body: |
            Automated release via CI.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets (.deb)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
