install(FILES BistableRulkovMapModel.h HodgkinHuxleyModel.h
	      RulkovMapModel.h FerdoMapModel.h MatsuokaModel.h
	      SimpleOscillatorModel.h HindmarshRoseModel.h RowatSelverstonModel.h
	      DiffusionSynapseModel.h #DiscreteDiffusionSynapseModel.h
	      IzhikevichModel.h GradualActivationSynapseModel.h VavoulisModel.h VavoulisCGCModelQ10.h               ChemicalSynapseModel.h
	      DESTINATION ${PROJECT_NAME}/${PROJECT_VERSION})
